# Generated by Django 3.2.9 on 2021-12-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20211227_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
