# Generated by Django 3.2.9 on 2021-12-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_delete_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='commerce.Item', verbose_name='items'),
        ),
    ]
