# Generated by Django 3.2.9 on 2021-12-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', editable=False, upload_to='product/', verbose_name='image'),
        ),
    ]
